<a href="https://colab.research.google.com/github/ndawinata/googleCO/blob/master/array_dan_matrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

In [0]:
arr2d = np.array([[1,2,3],[4,5,6]])
arr1d = np.array([1,1,1])
arr1d + arr2d

array([[2, 3, 4],
       [5, 6, 7]])

In [0]:
mx1 = np.matrix([1,2,3])
mx2 = np.matrix([[2],[2],[2]])
mx3 = np.matrix([2,2,2])
mx4 = np.matrix([[1,2,3],[2,3,4],[3,4,5]])
mx5 = np.matrix([[1,1,1],[1,1,1],[1,1,1]])
mx5

matrix([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])

In [0]:
mx4 + mx5

matrix([[2, 3, 4],
        [3, 4, 5],
        [4, 5, 6]])

In [0]:
mx4 * mx5

matrix([[ 6,  6,  6],
        [ 9,  9,  9],
        [12, 12, 12]])

In [0]:
mx1*mx5

matrix([[6, 6, 6]])

In [0]:
#cek ordo
mx1.shape

(1, 3)

In [0]:
#cek element
mx4.size

9

In [0]:
#merubah ordo
mx1.reshape(3,1)

matrix([[1],
        [2],
        [3]])

In [0]:
#membuat matrik zero
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [0]:
#membuat matrix identitas
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [0]:
#membuat matrix linier
#(start,stop,step)
np.arange(1,10,1)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [0]:
#membuat linier pembagian tepat
np.linspace(1,10,6)

array([ 1. ,  2.8,  4.6,  6.4,  8.2, 10. ])

In [0]:
#mengetahui type array
mx1.dtype

dtype('int64')

In [0]:
#rubah type

mxx= mx1.astype('float64')
mxx.dtype

dtype('float64')

In [0]:
#buat array random
np.random.random((3,3))

array([[0.34734572, 0.25276773, 0.94423684],
       [0.29390157, 0.01434938, 0.56616046],
       [0.638624  , 0.97804938, 0.76110116]])

In [0]:
mx7 = np.random.random((3,3))
mx7

array([[0.79961171, 0.71381969, 0.96991229],
       [0.84812639, 0.25968341, 0.1730369 ],
       [0.21216005, 0.02135831, 0.31362205]])

In [0]:
mxy= mx7.astype('int64')
mxy

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [0]:
#randint(low, high=None, size=None, dtype='l')
cek = np.random.randint(1,10,(3,3))
cek

array([[1, 5, 4],
       [3, 3, 1],
       [2, 6, 3]])

In [0]:
cek.min()

1

In [0]:
cek.max()

6

In [0]:
cek.mean()

3.111111111111111

In [0]:
#standart deviasi
cek.std()

1.5947444549341472

In [0]:
#cek variasi
cek.var()

2.54320987654321